### ISSUE TITLE
截止1.0.4版本Docker部署还是无法通过指定安全入口访问后台

### ISSUE THREAD

**Issue by aihttp** [allinssl/allinssl#171]
截止当前最新版本1.0.4，还是没有修复Docker全新部署后无法通过指定安全入口访问后台，也就是安全入口参数值在第一次启动没有生效。

镜像版本号：1.0.4
部署方式：Docker-compose
容器编排模板：{仅贴出核心配置}
   ```
    allinssl:
    image: allinssl/allinssl:latest
    container_name: allinssl
    restart: unless-stopped
    mem_limit: 100m
    ports:
      - "8888:8888"
    environment:
      - TZ=Asia/Shanghai
      - ALLINSSL_USER=testuser
      - ALLINSSL_PWD=testpwd
      - ALLINSSL_URL=allinssl
    volumes:
      - /www/wwwroot/ssl.test.com/data:/www/allinssl/data
 ```

部署成功后，浏览器访问【ssl.test.com/allinssl】会报404错误，进入容器内终端执行【./allinssl 15】获取面板运行地址：

```
 外网面板地址:      http://ip:8888/YuVPx9ZF  
 内网面板地址:      http://172.21.0.2:8888/YuVPx9ZF  
 用户名:      testuser  
 密码:       ******** 
```

说明在容器编排模板中指定的安全入口参数值没有生效，首次启动还是自动生成随机安全入口。

实际测试：在首次运行后进入后台修改一次安全入口，以后才能持续生效。

但是总不能要求新用户Docker部署都得进入容器内先查看随机生成的安全入口才能进控制台吧，期待优化下体验。
