### ISSUE TITLE
自动化部署工作流，本地部署失败，提示“[ERROR] 2025-06-29 20:28:50 - 前置命令执行失败: exec: "bash": executable file not found in $PATH, ”

### ISSUE THREAD

**Issue by WangZhiLoong** [allinssl/allinssl#255]
![Image](https://github.com/user-attachments/assets/921a0c53-f28b-43ed-8804-53db08ff7d4d)

**Comment by Truelovefortony** [comment]
是用docker部署的吧，要在容器里面执行apk add bash初始化

**Comment by dxkrs** [comment]
应该判断是用bash、ash或dash，如果是用sh就更通用了

**Comment by 928871247** [comment]
飞牛遇到同样的问题，不是容器环境

**Comment by githudk** [comment]
我也遇到了相同的问题，目前还没解决，有大佬知道原因和解决方案吗？

**Comment by CHD073** [comment]
同样，问题还是太多了，没法正常用

**Comment by githudk** [comment]
这个问题我已经有临时解决方案了:https://club.fnnas.com/forum.php?mod=viewthread&tid=62739&highlight=

**Comment by uni-lovelDragon** [comment]
可以这样
```yaml
services:
  allinssl:
    image: allinssl/allinssl:latest
    ports:
      - "8888:8888"
    volumes:
      - ./data:/www/allinssl/data
    environment:
      - TZ=Asia/Shanghai
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        # 替换阿里alpine源
        sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories;
        apk update && apk add --no-cache bash tzdata;
        exec /entrypoint.sh
```
